"""Weekly observed rainfall for the valley-3D hindcast (History mode rain).

Fetches ~3 years of DAILY rainfall from the EA Hydrology archive API for the
gauges nearest the prototype block, sums them onto the SAME Monday week axis
stations.js already carries (built by build_valley_stations), and writes a
tiny classic-script global. The scene rains on the block while the History
scrubber walks a wet week — the recharge story told with measurements.

The block mm is the MEAN across reporting gauges (a catchment-scale
indication, not a gridded product); weeks where no gauge reports are null.

Usage:
  python -m scripts.build_valley_rainfall --js web/valley/test/rainfall.js
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATIONS_JS = ROOT / "web/valley/test/stations.js"
HYDRO = "https://environment.data.gov.uk/hydrology/id"
CENTRE = (-1.43, 51.085)          # block centre (lon, lat)
DIST_KM = 24
MAX_GAUGES = 6


def _get(url: str):
    req = urllib.request.Request(url, headers={"User-Agent": "GWC-valley3d-rain"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.load(r)


def history_weeks():
    txt = STATIONS_JS.read_text(encoding="ascii")
    data = json.loads(re.search(r"window\.TEST3D_STATIONS = (.*);", txt).group(1))
    weeks = data.get("historyWeeks")
    if not weeks:
        raise SystemExit("stations.js has no historyWeeks — rebuild it first "
                         "(python -m scripts.build_valley_stations)")
    return weeks


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--js", type=Path, required=True)
    args = ap.parse_args()

    weeks = history_weeks()
    d0 = weeks[0]
    d1 = (dt.date.fromisoformat(weeks[-1]) + dt.timedelta(days=6)).isoformat()

    lon, lat = CENTRE
    st = _get(f"{HYDRO}/stations.json?observedProperty=rainfall"
              f"&lat={lat}&long={lon}&dist={DIST_KM}&_limit=50").get("items", [])
    st.sort(key=lambda s: (s.get("lat", 0) - lat) ** 2 + (s.get("long", 0) - lon) ** 2)
    gauges, daily = [], {}
    for s in st:
        if len(gauges) >= MAX_GAUGES:
            break
        try:
            measures = _get(s["@id"] + "/measures.json").get("items", [])
        except Exception:
            continue
        meas = next((m["notation"] for m in measures
                     if "-rainfall-t-86400-" in m["notation"]), None)
        if not meas:
            continue
        try:
            rows = _get(f"{HYDRO}/measures/{urllib.parse.quote(meas)}/readings.json"
                        f"?mineq-date={d0}&maxeq-date={d1}&_limit=2000").get("items", [])
        except Exception:
            continue
        vals = {r["date"]: r["value"] for r in rows if r.get("value") is not None}
        if len(vals) < 200:                       # a gauge needs a real record
            continue
        daily[s["label"]] = vals
        gauges.append({"name": s["label"], "lat": round(s["lat"], 4),
                       "lon": round(s["long"], 4)})
        print(f"  {s['label']}: {len(vals)} daily values")
    if not gauges:
        print("no usable rain gauges — nothing written", file=sys.stderr)
        return 2

    mm = []
    for wk in weeks:
        monday = dt.date.fromisoformat(wk)
        days = [(monday + dt.timedelta(days=i)).isoformat() for i in range(7)]
        per_gauge = []
        for vals in daily.values():
            got = [vals[d] for d in days if d in vals]
            if len(got) >= 5:                     # ≥5 of 7 days else no total
                per_gauge.append(sum(got))
        mm.append(round(sum(per_gauge) / len(per_gauge), 1) if per_gauge else None)

    n_ok = sum(v is not None for v in mm)
    payload = {
        "source": "EA Hydrology API daily rainfall (OGL v3), mean of "
                  f"{len(gauges)} gauges near the Test block",
        "note": "weekly totals on the stations.js Monday axis; catchment-scale "
                "indication, not a gridded product",
        "gauges": gauges,
        "mm": mm,
    }
    args.js.write_text(
        "// Generated by scripts/build_valley_rainfall.py.\n"
        "// Contains EA data (c) Environment Agency, OGL v3.\n"
        f"window.TEST3D_RAIN = {json.dumps(payload)};\n", encoding="ascii")
    tot = [v for v in mm if v is not None]
    print(f"{n_ok}/{len(weeks)} weeks covered, {min(tot):.0f}-{max(tot):.0f} mm/wk "
          f"-> {args.js} ({args.js.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
