"""Abstraction licence points — the shared ingest (valley-3D step 4 / H7 §3).

Source: EA "Water Rights Trading" NALD extract (OGL v3) — one row per licence
with abstraction-point Eastings/Northings, source type (groundwater / surface
water), purpose, and licensed max quantities. Download (~2 MB xlsx, updated
~annually; the filename really does start "Help for"):

  curl -L -o data/raw/abstraction/licence_trading_jan2025.xlsx \\
    'https://environment.data.gov.uk/api/file/download?fileDataSetId=f0a06c3a-8388-4a0f-9f38-eccb08e3d26d&fileName=Help%20for%20Licence%20Trading%20map%20data%20January%202025.xlsx'

One ingest, three consumers:
the 3-D abstraction layer, the H7 abstraction screen's capture-zone join, and
per-gauge low-flow context.

Honesty / privacy invariants baked in here, not left to consumers:
- **Holder names and addresses are STRIPPED** — many licence holders are
  individuals; the public register exists, but we don't republish personal
  data. Licence number is kept (the public join key).
- Quantities are **licensed capacity, not actual pumping** (no live feed
  exists), and a multi-point/multi-purpose licence repeats its LICENCE-level
  maxima on every row — never sum quantities across rows.
- The extract covers licences abstracting >100 m³/day that submit returns;
  some licences (incl. security-sensitive public-supply sources) are excluded.

Outputs:
  data/processed/abstraction_points.csv    national, privacy-stripped
  --js PATH                                bbox slice for the 3-D prototype
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

from scripts.build_terrain_tile import wgs84_to_osgb
from scripts.build_valley_rivers import osgb_to_wgs84

ROOT = Path(__file__).resolve().parents[1]
XLSX = ROOT / "data/raw/abstraction/licence_trading_jan2025.xlsx"
OUT_CSV = ROOT / "data/processed/abstraction_points.csv"
DEFAULT_BBOX = (-1.66, 50.87, -1.20, 51.30)
VINTAGE = "2025-01"

KEEP = {
    "Licence Number": "licence_no",
    "Source Type": "source",
    "Purpose": "purpose",
    "Category": "category",
    "Max Annual Quantity m3": "max_annual_m3",
    "Max Daily Quantity m3": "max_daily_m3",
    "Catchment": "catchment",
    "Eastings": "easting",
    "Northings": "northing",
}


def build() -> pd.DataFrame:
    df = pd.read_excel(XLSX, sheet_name="Data")
    df = df[list(KEEP)].rename(columns=KEEP)
    df = df.dropna(subset=["easting", "northing"])
    lonlat = [osgb_to_wgs84(e, n) for e, n in zip(df["easting"], df["northing"])]
    df["lon"] = [round(x[0], 5) for x in lonlat]
    df["lat"] = [round(x[1], 5) for x in lonlat]
    df["source"] = df["source"].str.strip()
    df["vintage"] = VINTAGE
    return df.reset_index(drop=True)


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bbox", nargs=4, type=float,
                    metavar=("LONMIN", "LATMIN", "LONMAX", "LATMAX"),
                    default=list(DEFAULT_BBOX))
    ap.add_argument("--js", type=Path,
                    help="also write a bbox slice as a classic-script global")
    args = ap.parse_args()
    if not XLSX.exists():
        print(f"ERROR: {XLSX} missing — see the module docstring for the "
              "download command.", file=sys.stderr)
        return 2
    df = build()
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUT_CSV, index=False)
    print(f"{len(df)} licence points → {OUT_CSV.relative_to(ROOT)} "
          f"(GW {int((df['source'] == 'Groundwater').sum())}, "
          f"SW {int((df['source'] == 'Surface water').sum())})")

    if args.js:
        lon_min, lat_min, lon_max, lat_max = args.bbox
        m = df[(df["lon"] >= lon_min) & (df["lon"] <= lon_max)
               & (df["lat"] >= lat_min) & (df["lat"] <= lat_max)]
        pts = [{
            "licence": r["licence_no"], "source": r["source"],
            "purpose": r["purpose"],
            "maxDaily": None if pd.isna(r["max_daily_m3"]) else round(float(r["max_daily_m3"]), 1),
            "maxAnnual": None if pd.isna(r["max_annual_m3"]) else round(float(r["max_annual_m3"]), 1),
            "lon": r["lon"], "lat": r["lat"],
        } for _, r in m.iterrows()]
        payload = {
            "source": "EA Water Rights Trading NALD extract (OGL v3), "
                      f"licence data as of {VINTAGE}",
            "note": "licensed capacity, NOT live pumping; >100 m3/day "
                    "returns-submitting licences only; some licences "
                    "(incl. security-sensitive supplies) excluded; quantities "
                    "are licence-level maxima",
            "points": pts,
        }
        args.js.write_text(
            "// Generated by scripts/build_abstraction_points.py.\n"
            "// EA Water Rights Trading extract (OGL v3). Holder names/addresses\n"
            "// deliberately stripped (personal data).\n"
            f"window.TEST3D_ABSTRACTION = {json.dumps(payload)};\n",
            encoding="ascii")
        print(f"wrote {args.js} ({len(pts)} points in bbox)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
